---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: yublueos
# description will be included in the image's metadata
description: Personalized Universal Blue (Silverblue) bootc Image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: bootc-update
        destination: /usr/lib/systemd/system

  - type: dnf
    repos:
      files:
        - mullvad.repo
        - 1password.repo
        - brave-browser.repo
        - code.repo
        - tailscale-stable.repo
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        - https://downloads.1password.com/linux/keys/1password.asc
        - https://packages.microsoft.com/keys/microsoft.asc
        - https://pkgs.tailscale.com/stable/fedora/repo.gpg
      copr:
        - atim/starship
      nonfree: rpmfusion
    install:
      skip-unavailable: true
      skip-broken: false
      packages:
        - brave-browser
        - mullvad-vpn
        - 1password
        - 1password-cli
        - code
        - gcc
        - p7zip
        - p7zip-plugins
        - starship
        - tailscale
        - unrar
        - virt-manager
        - libvirt
        - qemu-kvm
        - virt-install
        - virt-viewer
        - https://github.com/Eugeny/tabby/releases/download/v1.0.223/tabby-1.0.223-linux-x64.rpm
        # Gnome Extensions
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-blur-my-shell
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-freon
        - gnome-shell-extension-user-theme
    optfix:
      - 1Password
      - brave.com
      - Mullvad VPN
      - Tabby
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-shell-extension-background-logo
        - gnome-shell-extension-apps-menu

  - type: brew
    auto-update: true
    auto-upgrade: false

  - type: gnome-extensions
    install:
      - 6139 # Tailscale QS
      # - 5489 # Search Light
      # - 3193 # Blur my Shell
      # - 2890 # Tray Icons Reloaded
      # - 615 # AppIndicator and KStatusNotifierItem Support
      # - 307 # Dash to Dock
    # uninstall:
    #   - GSConnect # Uninstall step here should be used only for the extensions
    #     # which are not installed through OS package manager in the base image,
    #     # like extensions installed from gnome-extensions module

  - type: gschema-overrides
    include:
      - zz0-ublue-modifications.gschema.override

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # Custom
        - com.discordapp.Discord
        - com.github.PintaProject.Pinta
        - com.ranfdev.DistroShelf
        - com.slack.Slack
        - de.haeckerfelix.Fragments
        - dev.geopjr.Tuba
        - dev.zed.Zed
        - it.mijorus.gearlever
        - md.obsidian.Obsidian
        - net.waterfox.waterfox
        - org.fedoraproject.MediaWriter
        - org.flameshot.Flameshot
        - org.telegram.desktop
        - org.telegram.desktop.webview
        - org.videolan.VLC
        - rest.insomnia.Insomnia
        # Defaults
        - com.github.rafostar.Clapper
        - com.github.tchx84.Flatseal
        - io.github.flattool.Ignition
        - io.github.flattool.Warehouse
        - io.github.input_leap.input-leap
        - io.gitlab.adhami3310.Impression
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.DejaDup
        - org.gnome.Papers
        - com.mattjakeman.ExtensionManager
        - org.gnome.FileRoller
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.World.PikaBackup
        - org.gnome.SimpleScan
        - org.gnome.TextEditor
        - org.gnome.Weather
        - io.missioncenter.MissionCenter
        - io.github.pwr_solaar.solaar
        - org.gustavoperedo.FontDownloader
        - page.tesk.Refine
      remove:
        - org.gnome.eog
        - org.mozilla.firefox
    user: {} # Also add Flathub user repo, but no user packages

  - type: systemd
    system:
      masked:
        - ublue-update.timer
        - rpm-ostreed-automatic.timer
      enabled:
        - bootc-fetch-apply-updates.timer
        - mullvad-daemon
        - tailscaled
        - libvirtd

  - type: script
    snippets:
      - "chmod +x /etc/profile.d/run-brew-setup.sh"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
